port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

    - name: 'Example'
      path: './plugins/siriproxy-example'

    # - name: 'Thermostat'
    #   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
    #   host: '192.168.2.71' 

    - name: 'Twitter'
      git: 'git://github.com/netpro2k/SiriProxy-Twitter.git' # path works just like specifing in gemfile 
      consumer_key: "EtV07DWudLWvtsaivEk1w" 
      consumer_secret: "tFFJwPJEW0sJZctG0CorMm6oAIrqvgBMEMtyOyVg"
      oauth_token: "14288790-4385a4ETyG7qPwCc071XmpmcQq8hEaJFg6070dkEW" 
      oauth_token_secret: "idDUICQl9WjWaAzYLC35KDX1Fr95s3N1J9GfBmqxi2s"

    # Note: Eliza should not be run with other plugins
    # - name: 'Eliza'
    #   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile 

    # Below are not actual plugins, just further example of config options

    # - SimplePlugin # simple syntax for plugins that are in rubygems and have no config 

    # - name: 'AnotherPlugin'
    #   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying in Gemfile
